src/Entity/User.php
<?php

namespace App\Entity;

use DateTime;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private string $pseudo;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private string $sex;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private string $level;

    /**
     * @ORM\Column(type="date")
     */
    private DateTimeInterface $birthdate;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private string $address;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private string $postalcode;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private string $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $description;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private string $email;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private string $phone;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getSex(): ?string
    {
        return $this->sex;
    }

    public function setSex(string $sex): self
    {
        $this->sex = $sex;

        return $this;
    }

    public function getLevel(): ?string
    {
        return $this->level;
    }

    public function setLevel(string $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getBirthdate(): ?\DateTimeInterface
    {
        return $this->birthdate;
    }

    public function setBirthdate(\DateTimeInterface $birthdate): self
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    public function getAge(): int
    {
        $dateInterval = $this->birthdate->diff(new DateTime());

        return $dateInterval->y;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalcode(): ?string
    {
        return $this->postalcode;
    }

    public function setPostalcode(?string $postalcode): self
    {
        $this->postalcode = $postalcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }
}

src/Controller/SearchController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\SearchUserType;
use App\Repository\UserRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

 /**
* @Route("/search", name="search_")
*/
class SearchController extends AbstractController
{
    /**
     * @Route("/", name="users")
     */
    public function search(Request $request, UserRepository $userRepository): Response
    {
        $users = new User();
        $searchUserForm = $this->createForm(SearchUserType::class, $users);
        $searchUserForm->handleRequest($request);

        if ($searchUserForm->isSubmitted() && $searchUserForm->isValid()) {
            $level = $users->getLevel();
            $sex = $users->getSex();
            $users = $userRepository->search($level, $sex);
        } else {
            $users = $userRepository->findAll();
        }
        return $this->render('search/index.html.twig', [
            'searchForm' => $searchUserForm->createView(),
            'users' => $users,
        ]);
    }
}

templates/search/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SearchController!{% endblock %}

{% block body %}
    <div class="backgroundSearchUsers">
        {{ form_start(searchForm) }}
            <div class="col">
                <div class="row">
                    {{ form_row(searchForm.level, ) }}
                </div>
                <div class="row">
                    {{ form_row(searchForm.sex, { 'attr': {'class': 'xxx'} }) }}
                </div>
                <button>Rechercher</button>
            </div>
        {{ form_end(searchForm) }}

        <div class='searchcontainer'>
            <h2 class='resultSearch'>Résultat de votre Recherche</h2> 
                {% for user in users %}
                    <div class='players'>
                        <img class='playerPhoto' src="https://picsum.photos/100" alt="avatar">
                            <div class="container_1_players">
                                <p class='playerItem playerPseudo'>{{user.pseudo}}</p>
                                <p class='playerItem playerSex'>{{user.sex}}</p>
                                <p class='playerItem playerAge'>{{user.age}}ans</p>
                                <p class='playerItem playerLevel'>{{user.level}}</p>
                            </div>
                    </div>
                {% endfor %}
        </div>
    </div>
{% endblock %}